spring:
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "product-DB"
      username: "root"
      password: "example"
      authentication-database : "admin"
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: "DEBUG"